import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

// 컴포넌트 불러오기
import Navbar from '@/components/common/Navbar';
import Footer from '@/components/common/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: '안남시',
  description: 'Generated by create next app',
  icons: {
    icon: '/Annam-logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* 상단 네비게이션 */}
        <Navbar />

        {/* 페이지 본문 */}
        <main className="flex-1">{children}</main>

        {/* 하단 푸터 */}
        <Footer />
      </body>
    </html>
  );
}
